/**
 * Downloads Google Fonts CSS and inlines all woff2 files as base64 data URIs.
 * Run before the singlefile build: tsx scripts/download-fonts.ts
 *
 * Output: client/src/generated/fonts.css
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");
const OUTPUT_PATH = path.resolve(PROJECT_ROOT, "client", "src", "generated", "fonts.css");

// Google Fonts CSS endpoints — request woff2 format for modern browsers
const FONT_URLS = [
  "https://fonts.googleapis.com/css2?family=Libre+Caslon+Text:wght@400;700&family=Hanken+Grotesk:wght@400;600;700&display=swap",
  "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap",
];

// Pretend to be Chrome on Windows to receive woff2 (most compressed)
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

async function fetchGoogleFontsCSS(url: string): Promise<string> {
  const resp = await fetch(url, { headers: { "User-Agent": UA } });
  if (!resp.ok) {
    throw new Error(`Failed to fetch ${url}: ${resp.status} ${resp.statusText}`);
  }
  return resp.text();
}

function extractWoff2Urls(css: string): string[] {
  const urls = new Set<string>();
  // Match url(https://fonts.gstatic.com/...) format=woff2
  const re = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g;
  let match;
  while ((match = re.exec(css)) !== null) {
    urls.add(match[1]);
  }
  return [...urls];
}

async function downloadWoff2(url: string): Promise<Buffer> {
  // Retry up to 3 times
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const resp = await fetch(url);
      if (!resp.ok) throw new Error(`Status ${resp.status}`);
      return Buffer.from(await resp.arrayBuffer());
    } catch (err) {
      if (attempt === 3) throw err;
      console.warn(`  Retry ${attempt}/3 for ${url.split("/").pop()}: ${err}`);
      await new Promise(r => setTimeout(r, 1000));
    }
  }
  throw new Error("unreachable");
}

async function main() {
  console.log("🔤 Downloading Google Fonts for singlefile build...\n");

  // Ensure output directory exists
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });

  let combinedCSS = `/* Generated by scripts/download-fonts.ts — DO NOT EDIT */\n`;
  combinedCSS += `/* Google Fonts with base64-encoded woff2 for offline support */\n\n`;

  for (const fontUrl of FONT_URLS) {
    const label = fontUrl.includes("Material+Symbols") ? "Material Symbols Outlined" : "Libre Caslon Text + Hanken Grotesk";
    console.log(`  Fetching CSS: ${label}`);
    let css = await fetchGoogleFontsCSS(fontUrl);

    const woff2Urls = extractWoff2Urls(css);
    console.log(`  Found ${woff2Urls.length} woff2 file(s)`);

    for (const woff2Url of woff2Urls) {
      const filename = woff2Url.split("/").pop() || "font.woff2";
      process.stdout.write(`    Downloading ${filename}... `);
      const buf = await downloadWoff2(woff2Url);
      const b64 = buf.toString("base64");
      const dataUri = `data:font/woff2;base64,${b64}`;
      // Replace URL with data URI (escape for regex)
      const escaped = woff2Url.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      css = css.replace(new RegExp(escaped, "g"), dataUri);
      const kb = (buf.length / 1024).toFixed(1);
      console.log(`${kb} KB ✓`);
    }

    combinedCSS += css + "\n";
  }

  // Add Material Symbols utility class (normally injected by Google's loader)
  combinedCSS += `
/* Material Symbols utility class (normally provided by Google Fonts loader) */
.material-symbols-outlined {
  font-family: 'Material Symbols Outlined';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
  font-variation-settings:
    'FILL' 0,
    'wght' 400,
    'GRAD' 0,
    'opsz' 24;
}

.material-symbols-outlined.fill-1 {
  font-variation-settings:
    'FILL' 1,
    'wght' 400,
    'GRAD' 0,
    'opsz' 24;
}
`;

  fs.writeFileSync(OUTPUT_PATH, combinedCSS, "utf-8");
  const sizeKB = (Buffer.byteLength(combinedCSS, "utf-8") / 1024).toFixed(1);
  console.log(`\n✅ Written ${OUTPUT_PATH} (${sizeKB} KB)`);
}

main().catch(err => {
  console.error("❌ Font download failed:", err);
  process.exit(1);
});
